gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Y ahora dime...\n"
    .string "¿eres chico o chica?$"

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "¡Hola!\n"
    .string "Espero que estés bien.\p"
    .string "Mi nombre es OAK.\p"
    .string "Muchos me conocen como\n"
    .string "el PROFESOR OAK...\p$"

gOakSpeech_Text_ThisWorld::
    .string "La LIGA POKéMON siempre está\n"
    .string "buscando personas con talento.\p$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "Y recientemente hemos\n"
    .string "encontrado una oportunidad\p"
    .string "que podría encajar contigo.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "Hay un gimnasio que está\n"
    .string "buscando a alguien\p"
    .string "con un perfil como el tuyo.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Y en la LIGA POKéMON estamos\n"
    .string "convencidos de que tienes un\p"
    .string "gran potencial para el puesto.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Ehh... disculpa, te llamabas...\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Ah, sí... ya recuerdo.\n"
    .string "Eres {PLAYER}, ¿verdad?$"

gOakSpeech_Text_WhatWasHisName::
    .string "Por supuesto {PLAYER},\n"
    .string "te decía....\p"
    .string "BROCK, el Líder de Gimnasio \n"
    .string "de Ciudad Plateada quiere\p"
    .string "conocerte y hablar contigo.\n"
    .string "Querrá saber qué puedes\p"
    .string "aportar a su equipo y valorar\n"
    .string "tu habilidad y potencial.\p$"

gOakSpeech_Text_LetsGo::
    .string "¿Qué me dices?\n"
    .string "¿Te interesa el trabajo?\p"
    .string "Es una oportunidad única,\p"
    .string "Te esperamos en el gimnasio\n"
    .string "de Ciudad Plateada.$"
