PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "Buenos días chavalín\n"
    .string "Recuerda, hoy es el gran día...\p"
    .string "En mis días de mozo no existían\n"
    .string "las entrevistas ni tantas tonterías... $"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Buenos diás hijo, \p"
    .string "Te he preparado tus pastelitos\n"
    .string "favoritos para el desayuno\p"
    .string "¿Sabes...? el vecino nuevo...\n"
    .string "ese tal GREEN...\p"
    .string "no es rival para ti\n"
    .string "¡Buena suerte hijo!$"

PewterCity_House2_Text_ObtainedASandshrew::
    .string "¡{PLAYER} consiguió un SANDSHREW!$"

PewterCity_House2_Text_DontForgetYourSandshrew::
    .string "Hijo no te olvides de\n"
    .string "llevarte a tu Sandrew.$"

