PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "Buenos días chavalín\n"
    .string "Recuerda, hoy es el gran día...\p"
    .string "En mis días de mozo, cuando picaba\n"
    .string "la dura piedra del monte Moon\p"
    .string "Cualquiera que tuviese ganas \n"
    .string "de incar el lomo estaba contratado \p"
    .string "No existian esas entrevistas\n"
    .string "ni tantas tonterías modernas$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Buenos diás hijo, \p"
    .string "Te he preparado los pastelitos\n"
    .string "favoritos de Cubone\p"
    .string "Los he dejado en tu bolsa...\p"
    .string "¿Sabes...? el vecino nuevo...\n"
    .string "ese tal GREEN...\p"
    .string "no es rival para ti\n"
    .string "¡Buena suerte hijo!$"

PewterCity_House2_Text_ObtainedASandshrew::
    .string "¡{PLAYER} consiguió un CUBONE!$"

PewterCity_House2_Text_DontForgetYourSandshrew::
    .string "Hijo no te olvides de\n"
    .string "llevarte a tu Cubone.$"

