ViridianForest_Text_FriendsItchingToBattle::
    .string "I came here with some friends to\n"
    .string "catch us some BUG POKéMON!\p"
    .string "They're all itching to get into\n"
    .string "some POKéMON battles!$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "No!\nCATERPIE can't hack it!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "You can't jam out if you're a\l"
    .string "POKéMON TRAINER!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "I ran out of POKéMON!$"

ViridianForest_Text_DougPostBattle::
    .string "That totally stinks! I'm going to\n"
    .string "catch some stronger ones!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat::
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle::
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "I lost some of my allowance…$"

ViridianForest_Text_CharlieIntro::
    .string "Did you know that POKéMON evolve?$"

ViridianForest_Text_CharlieDefeat::
    .string "Oh!\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKéMON evolve quickly.\n"
    .string "They're a lot of fun!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many POKé BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRAINER TIPS\p"
    .string "If your POKéMON are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "For poison, use ANTIDOTE!\n"
    .string "Get it at POKéMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "TRAINER TIPS\p"
    .string "Contact PROF. OAK via a PC to\n"
    .string "get your POKéDEX evaluated!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAINER TIPS\p"
    .string "You can't catch a POKéMON that\n"
    .string "belongs to someone else.\p"
    .string "Throw POKé BALLS only at wild\n"
    .string "POKéMON to catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TRAINER TIPS\p"
    .string "Weaken POKéMON before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"

ViridianForest_Text_CrystalSound::
    .string "Pareces oír un sonido agudo\n"
    .string "y cristalino…$"

ViridianForest_Text_MewVoice::
    .string "{COLOR RED}{SHADOW LIGHT_RED}MEW: … {PLAYER}, no temas…\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}soy un POKéMON biotraje ancestral…\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}llevo mucho tiempo esperándo que crecieras\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}para reunirme contigo\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}Tengo tantas cosas que contarte…\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}pero no mucho tiempo\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}hasta que me encuentren\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}la historia que conoces…\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}…está muy lejos de la verdad…\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}y ya has crecido lo suficiente\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}para entenderlo\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}…Ya llegan de nuevo…\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}tengo que marcharme…\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}ten cuidado y no hablas con nadie\p"
    .string "{COLOR RED}{SHADOW LIGHT_RED}Búscame en Ciudad Celeste.$"

ViridianForest_Text_AgathaConfront::
    .string "AGATHA: Tú, novato…\n"
    .string "Este lugar es peligroso\l"
    .string "¿Qué estás haciendo\p"
    .string "aquí?\n"
    .string "AGATHA: ¿Has visto a una\n"
    .string "criatura rosada flotante?$"

ViridianForest_Text_AgathaCallsLiar::
    .string "AGATHA: ¿Que solo buscabas\n"
    .string "musgo brillante? …\p"
    .string "AGATHA: Eres un pésimo\n"
    .string "mentiroso.\p"
    .string "AGATHA: Si no has visto nada,\n"
    .string "no te importará entregarme\l"
    .string "tu POKéDEX...$"

ViridianForest_Text_AgathaTruthful::
    .string "AGATHA: Al menos veo que no\n"
    .string "eres tan necio como para\l"
    .string "engañarme…\p"
    .string "AGATHA: Esa criatura es asunto\n"
    .string "de la Liga. Lo que hayas visto\l"
    .string "debe quedar registrado.\p"
    .string "AGATHA: ¡Arrestadlo y quitadle\n"
    .string "la POKéDEX!$"

ViridianForest_Text_SoldierDemandPokedex::
    .string "SOLDADO: ¡Entrega\n"
    .string "inmediatamente tu POKé…$"

ViridianForest_Text_AgathaOnixHere::
    .string "AGATHA: ¿Un ONIX aquí?\n"
    .string "Esta zona…$"

ViridianForest_Text_SoldierChase::
    .string "SOLDADO: ¿Los perseguimos?$"

ViridianForest_Text_AgathaRetreat1::
    .string "AGATHA: No, sigamos la señal\n"
    .string "de MEW, nada es más importante\l"
    .string "ahora.$"

ViridianForest_Text_AgathaRetreat2::
    .string "AGATHA: Además, seguramente\n"
    .string "ese chiquillo no siga con vida.$"

ViridianForest_Text_AgathaRetreat3::
    .string "AGATHA: La fuerza psíquica que\n"
    .string "usamos para detectar a MEW\l"
    .string "debió alterar a ese ONIX.\p"
    .string "AGATHA: ¡En marcha!$"
